---
- hosts: all
  tasks:
    - name: Forensics-Debug
      ansible.builtin.debug:
        msg: "received alert from deployment {{ ansible_eda.event.payload.alert.deployment.name }} in pod {{ ansible_eda.event.payload.alert.processViolation.processes[-1].podId }}"
    - name: KubeExec-Net
      kubernetes.core.k8s_exec:
        namespace: "{{ ansible_eda.event.payload.alert.namespace }}"
        pod: "{{ ansible_eda.event.payload.alert.processViolation.processes[-1].podId }}"
        command: 'netstat -nt'
      register: find_output
      ignore_errors: True
    - debug: var=find_output.stdout_lines
