---
- name: Webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
  rules:
    - name: debug
      condition: event.payload is defined
      enabled: false
      action:
        run_playbook:
          name: debug.yml

    - name: stackrox
      condition: event.payload.message == "stackrox"
      action:
        run_playbook:
          name: stackrox.yml
          json_mode: false

    - name: Forensics Run
      condition: event.payload.alert.policy.name == "Linux User Add Execution"
      action:
        run_playbook:
            name: forensics-find.yml
            json_mode: false
