---
- name: Webhook
  hosts: all

 ## Define our source for events
  sources:
   - ansible.eda.webhook:
       host: 0.0.0.0
       port: 5000

 ## Define the conditions we are looking for
  rules:
   - name: Say Hello
     condition: event.payload.message == "stackrox"

 ## Define the action we should take should the condition be met
     action:
       run_playbook:
         name: say-what.yml
